### ISSUE TITLE
feature request, an output for the package `here`

### ISSUE THREAD

**Issue by ginolhac** [konradedgar/reformatFilePath#1]
Hi,

nice add-in, would you consider to add an option for the [here](https://cran.r-project.org/web/packages/here/index.html)? Would be very nice.

Thanks again

**Comment by konradzdeb** [comment]
Hi, 
Sure, I’ll be happy to check this out. I’m currently on holiday but I’ll look into this late this months. Also, Feel free to make a PR if you have any suggestions.

Regards

--
Konrad

**Comment by ginolhac** [comment]
Thanks !
